### ISSUE TITLE
Don't understand how to build a solution

### ISSUE THREAD

**Issue by lyc-ch** [amciakx0/CCGenshin#11]
Error after debugging：
magic_enum.hpp”: No such file or directory 	cheat-base	D:\yuanshen\cheat-base\framework\pch.h	13
SimpleIni.h”: No such file or directory	injector	D:\yuanshen\cheat-base\src\cheat-base\util.h	9
.....

**Comment by amciakx0** [comment]
https://github.com/amciakx0/polygone
