### ISSUE TITLE
Doing new cheat for genshin impact :)

### ISSUE THREAD

**Issue by amciakx0** [amciakx0/CCGenshin#15]
If you got suggestions what to add, please tell me in comments below :)

**Comment by HHYWYH** [comment]
hope that the program can remember the size and position of the hovering window set last time, otherwise it needs to be reset every time it is opened (the default hovering window position will obscure the game map)

**Comment by amciakx0** [comment]
> 

Thanks :)

**Comment by LangQi99** [comment]
hope a function, press a button then tp the game mission location. or storage a hitomi position list that we can tp directly.

**Comment by LangQi99** [comment]
maybe tp the nearest ESP is more convenient

**Comment by amciakx0** [comment]
https://github.com/amciakx0/polygone
